<?php

namespace ContainerUtqyGbd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderSuccesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OrderSuccesController' shared autowired service.
     *
     * @return \App\Controller\OrderSuccesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/OrderSuccesController.php';

        $container->services['App\\Controller\\OrderSuccesController'] = $instance = new \App\Controller\OrderSuccesController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\OrderSuccesController', $container));

        return $instance;
    }
}
