<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBkAyHsS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBkAyHsS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBkAyHsS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBkAyHsS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBkAyHsS\App_KernelDevDebugContainer([
    'container.build_hash' => 'BkAyHsS',
    'container.build_id' => 'eb72b830',
    'container.build_time' => 1706771303,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBkAyHsS');
