<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entity\Order implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carrierName' => [parent::class, 'carrierName', null],
        "\0".parent::class."\0".'carrierPrice' => [parent::class, 'carrierPrice', null],
        "\0".parent::class."\0".'createAt' => [parent::class, 'createAt', null],
        "\0".parent::class."\0".'delivery' => [parent::class, 'delivery', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'orderDetails' => [parent::class, 'orderDetails', null],
        "\0".parent::class."\0".'reference' => [parent::class, 'reference', null],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null],
        "\0".parent::class."\0".'stripSessionId' => [parent::class, 'stripSessionId', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'carrierName' => [parent::class, 'carrierName', null],
        'carrierPrice' => [parent::class, 'carrierPrice', null],
        'createAt' => [parent::class, 'createAt', null],
        'delivery' => [parent::class, 'delivery', null],
        'id' => [parent::class, 'id', null],
        'orderDetails' => [parent::class, 'orderDetails', null],
        'reference' => [parent::class, 'reference', null],
        'state' => [parent::class, 'state', null],
        'stripSessionId' => [parent::class, 'stripSessionId', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
